###############################################################################
# Created by write_sdc
###############################################################################
current_design tt_um_echoworld424_tpv
###############################################################################
# Timing Constraints
###############################################################################
create_clock -name clk -period 20.0000 [get_ports {clk}]
set_clock_transition 0.1500 [get_clocks {clk}]
set_clock_uncertainty -setup 0.2500 clk
set_clock_uncertainty -hold 0.0500 clk
set_propagated_clock [get_clocks {clk}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ena}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {rst_n}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {ui_in[7]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[0]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[1]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[2]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[3]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[4]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[5]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[6]}]
set_input_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_in[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_oe[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uio_out[7]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[0]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[1]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[2]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[3]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[4]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[5]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[6]}]
set_output_delay 4.0000 -clock [get_clocks {clk}] -add_delay [get_ports {uo_out[7]}]
set_disable_timing [get_cells {u_ro_gen.g_tail[0].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[1].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[2].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[3].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[4].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[5].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[6].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.g_tail[7].u_t._cell}]
set_disable_timing [get_cells {u_ro_gen.u_close._cell}]
set_disable_timing [get_cells {u_ro_gen.u_gate.u_a1}]
set_disable_timing [get_cells {u_ro_gen.u_gate.u_a2}]
set_disable_timing [get_cells {u_ro_gen.u_gate.u_a3}]
set_disable_timing [get_cells {u_ro_gen.u_gate.u_im}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[0].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[10].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[11].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[12].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[13].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[14].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[15].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[16].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[17].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[18].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[19].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[1].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[20].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[21].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[22].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[23].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[24].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[25].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[26].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[27].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[28].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[29].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[2].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[30].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[31].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[32].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[33].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[34].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[35].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[36].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[37].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[38].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[39].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[3].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[40].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[41].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[4].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[5].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[6].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[7].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[8].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.g_inv[9].u_inv._cell}]
set_disable_timing [get_cells {u_ro_gen.u_line.u_mux.u_m0}]
set_disable_timing [get_cells {u_ro_gen.u_line.u_mux.u_m1}]
set_disable_timing [get_cells {u_ro_gen.u_line.u_mux.u_m2}]
set_disable_timing [get_cells {u_ro_mat.g_tail[0].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[1].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[2].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[3].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[4].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[5].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[6].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.g_tail[7].u_t._cell}]
set_disable_timing [get_cells {u_ro_mat.u_close._cell}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_a1}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_a1_108}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_a1_88}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_a2}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_o1}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_x1}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_x1_109}]
set_disable_timing [get_cells {u_ro_mat.u_f0.u_x1_89}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_a1}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_a1_110}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_a1_90}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_a2}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_o1}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_x1}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_x1_111}]
set_disable_timing [get_cells {u_ro_mat.u_f1.u_x1_91}]
set_disable_timing [get_cells {u_ro_mat.u_gate.u_a1}]
set_disable_timing [get_cells {u_ro_mat.u_gate.u_a2}]
set_disable_timing [get_cells {u_ro_mat.u_gate.u_a3}]
set_disable_timing [get_cells {u_ro_mat.u_gate.u_im}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[0].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[10].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[11].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[12].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[13].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[14].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[15].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[16].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[17].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[18].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[19].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[1].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[20].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[21].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[22].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[23].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[24].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[25].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[26].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[27].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[28].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[29].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[2].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[30].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[31].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[32].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[33].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[34].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[35].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[36].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[37].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[38].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[39].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[3].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[40].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[41].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[42].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[43].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[44].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[45].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[46].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[47].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[48].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[49].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[4].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[50].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[51].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[52].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[53].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[54].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[55].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[56].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[57].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[58].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[59].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[5].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[60].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[61].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[62].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[63].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[64].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[65].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[6].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[7].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[8].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.g_inv[9].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line0.u_mux.u_m0}]
set_disable_timing [get_cells {u_ro_mat.u_line0.u_mux.u_m1}]
set_disable_timing [get_cells {u_ro_mat.u_line0.u_mux.u_m2}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[0].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[10].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[11].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[12].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[13].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[14].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[15].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[16].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[17].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[18].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[19].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[1].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[20].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[21].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[22].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[23].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[24].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[25].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[26].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[27].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[28].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[29].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[2].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[30].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[31].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[32].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[33].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[34].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[35].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[36].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[37].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[38].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[39].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[3].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[40].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[41].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[42].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[43].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[44].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[45].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[46].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[47].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[48].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[49].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[4].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[50].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[51].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[52].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[53].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[54].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[55].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[56].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[57].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[58].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[59].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[5].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[60].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[61].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[62].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[63].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[64].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[65].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[6].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[7].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[8].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.g_inv[9].u_inv._cell}]
set_disable_timing [get_cells {u_ro_mat.u_line1.u_mux.u_m0}]
set_disable_timing [get_cells {u_ro_mat.u_line1.u_mux.u_m1}]
set_disable_timing [get_cells {u_ro_mat.u_line1.u_mux.u_m2}]
###############################################################################
# Environment
###############################################################################
set_load -pin_load 0.0060 [get_ports {uio_oe[7]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[6]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[5]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[4]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[3]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[2]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[1]}]
set_load -pin_load 0.0060 [get_ports {uio_oe[0]}]
set_load -pin_load 0.0060 [get_ports {uio_out[7]}]
set_load -pin_load 0.0060 [get_ports {uio_out[6]}]
set_load -pin_load 0.0060 [get_ports {uio_out[5]}]
set_load -pin_load 0.0060 [get_ports {uio_out[4]}]
set_load -pin_load 0.0060 [get_ports {uio_out[3]}]
set_load -pin_load 0.0060 [get_ports {uio_out[2]}]
set_load -pin_load 0.0060 [get_ports {uio_out[1]}]
set_load -pin_load 0.0060 [get_ports {uio_out[0]}]
set_load -pin_load 0.0060 [get_ports {uo_out[7]}]
set_load -pin_load 0.0060 [get_ports {uo_out[6]}]
set_load -pin_load 0.0060 [get_ports {uo_out[5]}]
set_load -pin_load 0.0060 [get_ports {uo_out[4]}]
set_load -pin_load 0.0060 [get_ports {uo_out[3]}]
set_load -pin_load 0.0060 [get_ports {uo_out[2]}]
set_load -pin_load 0.0060 [get_ports {uo_out[1]}]
set_load -pin_load 0.0060 [get_ports {uo_out[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {clk}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ena}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {rst_n}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {ui_in[0]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[7]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[6]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[5]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[4]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[3]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[2]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[1]}]
set_driving_cell -lib_cell sg13g2_buf_4 -pin {X} -input_transition_rise 0.0000 -input_transition_fall 0.0000 [get_ports {uio_in[0]}]
###############################################################################
# Design Rules
###############################################################################
set_max_fanout 100.0000 [current_design]
