#!/usr/bin/env python3
"""Derive the RO measurement window from the RTL boot/window sequence.

The counter-inclusive SPICE decks must drive the canary's `en` input with the
waveform the chip actually produces, not with a hand-picked constant.  This
tool simulates the top level (Icarus, `TPV_GDELAY` so the loops toggle) and
reports, for each requested configuration and external clock period, the clock
edges at which

  * reset is released,
  * `ro_en` rises (boot completes, so the ring starts),
  * `win_done` rises (the window counter reaches `win_thresh`),
  * `ro_en` falls (the ring is gated off and the ripple settles / is read).

Output: JSON with clock-edge indices, times and the effective gate-open
duration.  `run_ro_count_case.py --window` consumes `en_rise_ns` / `en_fall_ns`
derived from this file, so the deck boundary is traceable to the RTL rather
than to an assumption.

Usage:
  probe_ro_window.py --outdir runs/freeze-validation/window [--iverilog iverilog]
                     [--corners 10,50] [--cfg 0x0C00]
"""

import argparse
import json
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.normpath(os.path.join(HERE, "..", ".."))
SRC = os.path.join(REPO, "src")
SOURCES = ["tt_um_echoworld424_tpv.v", "tpv_cells.v", "tpv_delay_line.v",
           "tpv_rca16.v", "tpv_checker.v", "tpv_pattern_gen.v",
           "tpv_ro_canary.v"]

TB = r"""`default_nettype none
`timescale 1ns / 1ps
/* Generated by tools/ro/probe_ro_window.py: trace ro_en/win_done/boot. */
module tb_window_probe;
  localparam real TPERIOD_NS = `PERIOD_NS;
  localparam real RELEASE_CYCLES = `RELEASE_CYCLES;
  localparam [15:0] CFG = 16'h`CFG;

  reg         clk = 1'b0;
  reg         rst_n = 1'b0;
  reg         ena = 1'b1;
  reg  [7:0]  ui_in;
  reg  [7:0]  uio_in;
  wire [7:0]  uo_out, uio_out, uio_oe;
  integer     cyc = 0;

  initial begin
    ui_in  = CFG[7:0];
    uio_in = CFG[15:8];
  end

  tt_um_echoworld424_tpv dut (
      .ui_in(ui_in), .uo_out(uo_out), .uio_in(uio_in), .uio_out(uio_out),
      .uio_oe(uio_oe), .ena(ena), .clk(clk), .rst_n(rst_n));

  always #(TPERIOD_NS / 2.0) clk = ~clk;

  initial begin
    $timeformat(-9, 3, " ", 12);
    $display("PROBE period_ns=%0f release_cycles=%0f cfg=%04h",
             TPERIOD_NS, RELEASE_CYCLES, CFG);
    #(RELEASE_CYCLES * TPERIOD_NS) rst_n = 1'b1;
    $display("RELEASE %0t %0d", $time, cyc);
    #(TPERIOD_NS * 400.0);
    $display("STOP %0t %0d", $time, cyc);
    $finish;
  end

  /* One state line per clock edge while reset is released.  Fields:
     time(ns) cycle boot win_done ro_en win_cnt */
  always @(posedge clk) if (rst_n) begin
    cyc <= cyc + 1;
    $display("C %0t %0d %0d %b %b %0d", $time, cyc + 1, dut.boot,
             dut.win_done, dut.ro_en, dut.win_cnt);
  end
endmodule
"""


def build_tb(outdir, cfg, period_ns, release_cycles):
    os.makedirs(outdir, exist_ok=True)
    path = os.path.join(outdir, f"tb_window_{cfg:04x}_{period_ns:g}ns.v")
    text = TB.replace("`PERIOD_NS", f"{period_ns:g}").replace(
        "`RELEASE_CYCLES", f"{release_cycles:g}").replace("`CFG", f"{cfg:04x}")
    with open(path, "w") as fh:
        fh.write(text)
    return path


def run_probe(outdir, iverilog, cfg=0x0C00, period_ns=100.0,
              release_cycles=2.5):
    tb = build_tb(outdir, cfg, period_ns, release_cycles)
    vvp = os.path.join(outdir, os.path.basename(tb).replace(".v", ".vvp"))
    srcs = [os.path.join(SRC, s) for s in SOURCES]
    cmd = [iverilog, "-g2012", "-DTPV_GDELAY=1", "-o", vvp, "-s",
           "tb_window_probe", tb] + srcs
    comp = subprocess.run(cmd, capture_output=True, text=True)
    if comp.returncode != 0:
        raise SystemExit("iverilog failed:\n" + comp.stderr[-2000:])
    sim = subprocess.run([os.path.join(os.path.dirname(iverilog), "vvp"), vvp],
                         capture_output=True, text=True)
    if sim.returncode != 0:
        raise SystemExit("vvp failed:\n" + sim.stderr[-2000:])
    return parse(sim.stdout, period_ns, release_cycles, cfg)


def parse(text, period_ns, release_cycles, cfg):
    """Clock-edge indices and times of the window boundaries.

    The testbench prints one `C <t_ns> <cycle> <boot> <win_done> <ro_en>
    <win_cnt>` line per clock edge while reset is released, so the boundaries
    come from the recorded control waveform rather than from a transition
    detector on an `x`-initialised signal.
    """
    out = dict(cfg=f"0x{cfg:04X}", period_ns=period_ns,
               release_cycles=release_cycles,
               t_release_ns=None, t_stop_ns=None, cycles_observed=0,
               ro_en_rise=None, win_done_rise=None, ro_en_fall=None,
               cycles_open=None, open_duration_ns=None)
    trace = []
    for line in text.splitlines():
        f = line.split()
        if not f:
            continue
        if f[0] == "RELEASE":
            out["t_release_ns"] = float(f[1])
        elif f[0] == "STOP":
            out["t_stop_ns"] = float(f[1])
        elif f[0] == "C" and len(f) >= 7:
            trace.append(dict(t_ns=float(f[1]), cycle=int(f[2]), boot=f[3],
                              win_done=f[4], ro_en=f[5], win_cnt=f[6]))
    out["cycles_observed"] = len(trace)
    rises = [x for x in trace if x["ro_en"] == "1"]
    if rises:
        out["ro_en_rise"] = dict(t_ns=rises[0]["t_ns"],
                                 cycle=rises[0]["cycle"],
                                 win_cnt=rises[0]["win_cnt"])
        after = [x for x in trace if x["cycle"] > rises[0]["cycle"]]
        for x in after:
            if x["ro_en"] == "0":
                out["ro_en_fall"] = dict(t_ns=x["t_ns"], cycle=x["cycle"],
                                         win_cnt=x["win_cnt"])
                break
    for x in trace:
        if x["win_done"] == "1":
            out["win_done_rise"] = dict(t_ns=x["t_ns"], cycle=x["cycle"],
                                        win_cnt=x["win_cnt"])
            break
    if out["ro_en_rise"] and out["ro_en_fall"]:
        dur = out["ro_en_fall"]["t_ns"] - out["ro_en_rise"]["t_ns"]
        out["open_duration_ns"] = dur
        out["cycles_open"] = dur / period_ns
    return out


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--outdir", default=os.path.join(HERE, "window-probe"))
    ap.add_argument("--iverilog", default="iverilog")
    ap.add_argument("--clocks-mhz", default="10,50")
    ap.add_argument("--cfgs", default="0x0C00",
                    help="comma-separated cfg words (default can_sel=3,win_sel=0)")
    ap.add_argument("--release-cycles", type=float, default=2.5,
                    help="reset release time in clock periods, held across at "
                         "least one edge and deliberately off-edge")
    ap.add_argument("--json", default=None)
    a = ap.parse_args()
    rows = []
    for cfg_s in a.cfgs.split(","):
        cfg = int(cfg_s, 0)
        for f_mhz in [float(x) for x in a.clocks_mhz.split(",")]:
            r = run_probe(a.outdir, a.iverilog, cfg, 1000.0 / f_mhz,
                          a.release_cycles)
            rows.append(r)
            print(json.dumps(r), flush=True)
    if a.json:
        json.dump(rows, open(a.json, "w"), indent=1)
    return 0


if __name__ == "__main__":
    sys.exit(main())
