#!/usr/bin/env python3
# SPDX-FileCopyrightText: (c) 2026 ECHO-HELLO-WORLD424
# SPDX-License-Identifier: Apache-2.0
"""Build the final-submission build manifest (PRE_SILICON_ACTION_PLAN P2.2).

Records the build identity of the final hardening run (CI run 33839023290,
commit 1e31757e50080b19fa7642b8b9cd6822f64b1d11, branch proposal-canary) whose
artifacts are staged under artifacts/run-33839023290/:

  manifest.json  machine-readable: git/CI identity, per-file SHA-256 and size
                 for every staged file, signoff summary (per-corner setup/hold
                 worst slack, instance counts, utilization, DRC/LVS/antenna),
                 and the resolved design configuration.
  MANIFEST.md    human-readable summary with the headline hashes.

Deterministic and idempotent: identical staged inputs produce identical
content (only `generated_at` changes). Stdlib only, no network access; the
run identity and provenance come from tools/common.py and the staged
commit_id.json / resolved.json / metrics.json / 54-openroad-stapostpnr
reports, not from any live CI query.

Run: python3 tools/make_manifest.py
"""

import datetime
import hashlib
import json
import os
import re
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import common as C  # noqa: E402

RUN_DIR = C.RUN_DIR
RUN_ID = C.RUN_ID
RUN_URL = ("https://github.com/ECHO-HELLO-WORLD424/tinyint-ttihp26b"
           "/actions/runs/" + RUN_ID)
WORKFLOW = "gds.yaml"
CI_RUNNER = "GitHub Actions, TinyTapeout/tt-gds-action@ttihp26b (ihp-sg13g2 PDK)"

# Outputs generated by this script; excluded from the hashed file list.
GENERATED = ("manifest.json", "MANIFEST.md")

STA_DIR = os.path.join(RUN_DIR, "54-openroad-stapostpnr")

REPRODUCE = [
    "# RTL regression (devcontainer; /ttsetup/venv active):",
    "cd test && make clean && make   # inspect test/results.xml",
    "# Functional gate-level test with the staged final netlist:",
    "cp artifacts/run-%s/nl/tt_um_echoworld424_tpv.nl.v test/gate_level_netlist.v" % RUN_ID,
    "cd test && make clean && make GATES=yes",
    "# Hardening (canonical path): push to proposal-canary; GitHub Actions runs",
    "# TinyTapeout/tt-gds-action@ttihp26b with the ihp-sg13g2 PDK (gds +",
    "# precheck + GL tests + viewer). Redownload the archived artifact with:",
    "gh run download %s --repo ECHO-HELLO-WORLD424/tinyint-ttihp26b --name GDS_logs --dir /tmp/gds-%s" % (RUN_ID, RUN_ID),
    "# Experiment-specific case-analyzed STA (extracted, SPEF):",
    "python3 tools/run_experiment_sta.py",
    "# RO canary loop-delay prediction (broken-loop STA, SPEF):",
    "python3 tools/run_ro_predict.py",
    "# SDF back-annotated sweep (host-side docker wrapper):",
    "python3 tools/run_sdfsim.py",
    "# Rebuild this manifest:",
    "python3 tools/make_manifest.py",
]


def run_git(*args):
    return subprocess.run(["git"] + list(args), capture_output=True,
                          text=True, cwd=C.REPO, check=True).stdout.strip()


def sha256_file(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def utc_now_iso():
    return (datetime.datetime.now(datetime.timezone.utc)
            .replace(microsecond=0).isoformat().replace("+00:00", "Z"))


def load_json(path):
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def git_identity():
    dirty = run_git("status", "--porcelain") != ""
    return {
        "git_commit": run_git("rev-parse", "HEAD"),
        "branch": run_git("rev-parse", "--abbrev-ref", "HEAD"),
        "git_dirty": dirty,
    }


def ci_identity():
    """CI identity from the staged artifacts + pinned provenance."""
    commit_id = load_json(os.path.join(RUN_DIR, "commit_id.json"))
    resolved = load_json(os.path.join(RUN_DIR, "resolved.json"))
    meta = resolved.get("meta") or {}
    # PDK revision from the resolved PDK_ROOT path (CI ciel store layout).
    m = re.search(r"/versions/([0-9a-f]{40})", resolved.get("PDK_ROOT", ""))
    pdk_rev_ci = m.group(1) if m else None
    assert pdk_rev_ci is None or pdk_rev_ci == C.CIEL_PDK_REV, \
        "staged PDK revision differs from pinned tools/common.py value"
    return {
        "run_id": RUN_ID,
        "run_url": RUN_URL,
        "workflow": WORKFLOW,
        "ci_runner": CI_RUNNER,
        "commit_id_json": {
            "app": commit_id.get("app"),
            "repo": commit_id.get("repo"),
            "commit": commit_id.get("commit"),
            "workflow_url": commit_id.get("workflow_url"),
        },
        "tool_image": C.LL_IMAGE,
        "librelane_version": (meta or {}).get("librelane_version"),
        "sta_step": "54-openroad-stapostpnr",
        "sta_step_runtime": read_sta_runtime(),
        "pdk": resolved.get("PDK"),
        "pdk_ciel_rev": C.CIEL_PDK_REV,
        "pdk_ciel_rev_source": "resolved.json PDK_ROOT (== tools/common.py)",
    }


def read_sta_runtime():
    with open(os.path.join(STA_DIR, "runtime.txt"), encoding="utf-8") as f:
        return f.read().strip()


def hash_all_files():
    """Hash every file under RUN_DIR (excluding this script's outputs)."""
    files = {}
    for root, _dirs, names in os.walk(RUN_DIR):
        for name in sorted(names):
            if name in GENERATED:
                continue
            path = os.path.join(root, name)
            rel = os.path.relpath(path, RUN_DIR)
            files[rel] = {
                "size": os.path.getsize(path),
                "sha256": sha256_file(path),
            }
    return dict(sorted(files.items()))


def parse_summary_rpt():
    """Per-corner setup/hold worst slacks from sta summary.rpt.

    Columns (bar-separated): [0]=corner, [1]=hold worst slack, [2]=reg-to-reg
    hold, [3]=hold TNS, [4]=hold violation count, [6]=setup worst slack,
    [7]=reg-to-reg setup, [8]=setup TNS, [9]=setup violation count.
    """
    out = {}
    with open(os.path.join(STA_DIR, "summary.rpt"), encoding="utf-8") as f:
        for line in f:
            if "│" not in line:
                continue
            cols = [c.strip() for c in line.split("│")]
            if len(cols) < 10:
                continue
            corner = cols[0]
            if corner in ("", "Overall") or not corner.startswith("nom_"):
                continue
            out[corner] = {
                "hold_worst_slack_ns": float(cols[1]),
                "setup_worst_slack_ns": float(cols[6]),
                "hold_violations": int(cols[4]),
                "setup_violations": int(cols[9]),
            }
    return out


def extract_signoff():
    """Signoff numbers from metrics.json, cross-checked against summary.rpt."""
    metrics = load_json(os.path.join(RUN_DIR, "metrics.json"))
    corners = {}
    for corner in C.CORNER_NAMES:
        p = "__corner:" + corner
        corners[corner] = {
            "setup_worst_slack_ns": metrics["timing__setup__ws" + p],
            "setup_worst_slack_r2r_ns": metrics["timing__setup_r2r__ws" + p],
            "setup_tns_ns": metrics["timing__setup__tns" + p],
            "setup_violations": metrics["timing__setup_vio__count" + p],
            "hold_worst_slack_ns": metrics["timing__hold__ws" + p],
            "hold_worst_slack_r2r_ns": metrics["timing__hold_r2r__ws" + p],
            "hold_tns_ns": metrics["timing__hold__tns" + p],
            "hold_violations": metrics["timing__hold_vio__count" + p],
            "max_slew_violations": metrics[
                "design__max_slew_violation__count" + p],
            "max_fanout_violations": metrics[
                "design__max_fanout_violation__count" + p],
            "max_cap_violations": metrics[
                "design__max_cap_violation__count" + p],
        }
    # summary.rpt must agree with the metrics (report rounds to 4 decimals).
    for corner, vals in parse_summary_rpt().items():
        m = corners[corner]
        for key in ("setup_worst_slack_ns", "hold_worst_slack_ns"):
            assert abs(round(m[key], 4) - vals[key]) < 1e-9, \
                "summary.rpt vs metrics.json mismatch: %s %s" % (corner, key)
        assert m["setup_violations"] == vals["setup_violations"]
        assert m["hold_violations"] == vals["hold_violations"]

    def m(key):
        return metrics[key]

    drc_lvs = {
        "magic_drc_errors": m("magic__drc_error__count"),
        "magic_illegal_overlaps": m("magic__illegal_overlap__count"),
        "route_drc_errors": m("route__drc_errors"),
        "lvs_errors": m("design__lvs_error__count"),
        "lvs_device_differences": m("design__lvs_device_difference__count"),
        "lvs_net_differences": m("design__lvs_net_difference__count"),
        "lvs_property_fails": m("design__lvs_property_fail__count"),
        "antenna_violating_nets": m("antenna__violating__nets"),
        "antenna_violating_pins": m("antenna__violating__pins"),
        "route_antenna_violations": m("route__antenna_violation__count"),
        "power_grid_violations": m("design__power_grid_violation__count"),
    }
    if all(v == 0 for v in drc_lvs.values()):
        drc_lvs["note"] = ("all checks clean per staged metrics.json; the "
                           "DRC/LVS/antenna report files themselves are "
                           "recorded-in-CI-only at " + RUN_URL)
    else:
        drc_lvs["note"] = ("nonzero result(s) recorded in staged metrics.json;"
                           " see checker reports in the full CI artifact at "
                           + RUN_URL)
    drc_lvs["source"] = "artifacts/run-%s/metrics.json (staged subset)" % RUN_ID

    return {
        "corners": corners,
        "instances": {
            "total": m("design__instance__count"),
            "stdcell": m("design__instance__count__stdcell"),
            "fill": m("design__instance__count__class:fill_cell"),
            "total_area_um2": m("design__instance__area"),
            "stdcell_area_um2": m("design__instance__area__stdcell"),
        },
        "utilization": {
            "design": m("design__instance__utilization"),
            "stdcell": m("design__instance__utilization__stdcell"),
        },
        "drc_lvs_antenna": drc_lvs,
        "lint": {
            "errors": m("design__lint_error__count"),
            "warnings": m("design__lint_warning__count"),
            "inferred_latches": m("design__inferred_latch__count"),
        },
        "power_total_w": m("power__total"),
    }


def extract_config():
    """The timing/structure-affecting resolved configuration actually used."""
    r = load_json(os.path.join(RUN_DIR, "resolved.json"))

    def pick(*keys):
        return {k: r[k] for k in keys if k in r}

    cfg = pick(
        "PDK", "DESIGN_NAME", "CLOCK_PERIOD", "CLOCK_PORT",
        "VDD_PIN", "GND_PIN", "DIE_AREA", "FP_SIZING", "FP_CORE_UTIL",
        "PL_TARGET_DENSITY_PCT", "PL_TIMING_DRIVEN", "PL_ROUTABILITY_DRIVEN",
        "GRT_ADJUSTMENT", "GRT_LAYER_ADJUSTMENTS",
        "GRT_RESIZER_SETUP_SLACK_MARGIN", "GRT_RESIZER_HOLD_SLACK_MARGIN",
        "SYNTH_STRATEGY", "SYNTH_HIERARCHY_MODE", "SYNTH_ADDER_TYPE",
        "SYNTH_SIZING", "SYNTH_DRIVING_CELL", "SYNTH_TIE_UNDEFINED",
        "SYNTH_PARAMETERS", "USE_SLANG",
        "RT_MIN_LAYER", "RT_MAX_LAYER",
        "MAX_FANOUT_CONSTRAINT", "MAX_TRANSITION_CONSTRAINT",
        "MAX_CAPACITANCE_CONSTRAINT", "CLOCK_UNCERTAINTY_CONSTRAINT",
        "CLOCK_TRANSITION_CONSTRAINT", "TIME_DERATING_CONSTRAINT",
        "IO_DELAY_CONSTRAINT",
        "DRT_OPT_ITERS", "GRT_OVERFLOW_ITERS", "RUN_TAP_ENDCAP_INSERTION",
        "STA_CORNERS", "DEFAULT_CORNER", "HOLD_VIOLATION_CORNERS",
        "SIGNOFF_SDC_FILE",
    )
    # Keep paths as the names of the src files actually synthesized (CI
    # checkout paths are recorded in resolved.json itself).
    cfg["VERILOG_FILES"] = [os.path.basename(p) for p in r["VERILOG_FILES"]]
    cfg["SDC_FILE"] = "src/pnr.sdc"
    cfg["librelane_meta"] = r.get("meta")
    return cfg


def write_markdown(man, path):
    f = man["files"]
    gds = "gds/tt_um_echoworld424_tpv.gds"
    nl = "nl/tt_um_echoworld424_tpv.nl.v"
    spef = "spef/nom/tt_um_echoworld424_tpv.nom.spef"

    def h(rel):
        return "`%s`" % f[rel]["sha256"] if rel in f else "MISSING"

    lines = [
        "# Final submission build manifest (run %s)" % RUN_ID,
        "",
        "Generated by `tools/make_manifest.py`; machine-readable copy in",
        "`manifest.json` next to this file. Git-dirty flag at generation:",
        "**%s** (this manifest hashes the staged run artifacts, not the"
        " working tree)." % ("yes" if man["git"]["git_dirty"] else "no"),
        "",
        "| Item | Value |",
        "| --- | --- |",
        "| Commit | `%s` |" % man["git"]["staged_run_commit"],
        "| Branch | `%s` |" % man["git"]["branch"],
        "| CI run | [gds.yaml run %s](%s) (all green: gds + precheck + gl_test + viewer) |" % (RUN_ID, RUN_URL),
        "| Tool image | `%s` |" % man["ci"]["tool_image"],
        "| LibreLane | %s (resolved.json meta) |" % man["ci"]["librelane_version"],
        "| PDK | %s @ ciel `%s` |" % (man["ci"]["pdk"], man["ci"]["pdk_ciel_rev"]),
        "| STA step | %s (runtime %s) |" % (man["ci"]["sta_step"], man["ci"]["sta_step_runtime"]),
        "",
        "## Signoff summary",
        "",
        "| Corner | Setup worst slack (ns) | Hold worst slack (ns) | Setup TNS (ns) | Setup vio | Hold vio |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for corner, c in man["signoff"]["corners"].items():
        lines.append(
            "| %s | %+.4f | %+.4f | %+.4f | %d | %d |" % (
                corner, c["setup_worst_slack_ns"], c["hold_worst_slack_ns"],
                c["setup_tns_ns"], c["setup_violations"],
                c["hold_violations"]))
    inst = man["signoff"]["instances"]
    util = man["signoff"]["utilization"]
    d = man["signoff"]["drc_lvs_antenna"]
    lines += [
        "",
        "| Instances | Utilization | Magic DRC | Route DRC | LVS | Antenna | Power grid |",
        "| --- | --- | --- | --- | --- | --- | --- |",
        "| %d total (%d stdcell + %d fill) | %.2f%% design / %.2f%% stdcell | %d | %d | %d | %d | %d |" % (
            inst["total"], inst["stdcell"], inst["fill"],
            100 * util["design"], 100 * util["stdcell"],
            d["magic_drc_errors"], d["route_drc_errors"], d["lvs_errors"],
            d["route_antenna_violations"], d["power_grid_violations"]),
        "",
        "DRC/LVS/antenna values are recorded in the staged `metrics.json`;"
        " the checker report files themselves are recorded-in-CI-only"
        " ([run %s](%s))." % (RUN_ID, RUN_URL),
        "",
        "## Headline artifact hashes (SHA-256)",
        "",
        "| Artifact | Path | SHA-256 |",
        "| --- | --- | --- |",
        "| Final GDS | `%s` | %s |" % (gds, h(gds)),
        "| Final netlist | `%s` | %s |" % (nl, h(nl)),
        "| Nominal SPEF | `%s` | %s |" % (spef, h(spef)),
        "",
        "## Reproduce",
        "",
        "```sh",
    ] + man["reproduce"] + ["```"]
    with open(path, "w", encoding="utf-8") as fh:
        fh.write("\n".join(lines) + "\n")


def main():
    man = {
        "schema": {
            "name": "tpv-final-build-manifest",
            "version": 1,
            "generated_at": utc_now_iso(),
            "notes": ("Final submission build identity for "
                      "PRE_SILICON_ACTION_PLAN item P2.2; hashes cover the "
                      "staged run-33839023290 artifacts only."),
        },
        "git": dict(git_identity(), staged_run_commit=C.GIT_COMMIT),
        "ci": ci_identity(),
        "config": extract_config(),
        "signoff": extract_signoff(),
        "files": hash_all_files(),
        "reproduce": REPRODUCE,
    }
    man_path = os.path.join(RUN_DIR, "manifest.json")
    with open(man_path, "w", encoding="utf-8") as fh:
        json.dump(man, fh, indent=2)
        fh.write("\n")
    write_markdown(man, os.path.join(RUN_DIR, "MANIFEST.md"))
    print("wrote", man_path)
    print("wrote", os.path.join(RUN_DIR, "MANIFEST.md"))
    print("hashed", len(man["files"]), "files")


if __name__ == "__main__":
    main()
